2022-02-18 13:04:58,755 INFO    MainThread:4550 [wandb_setup.py:_flush():71] setting env: {}
2022-02-18 13:04:58,755 INFO    MainThread:4550 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-18 13:04:58,755 INFO    MainThread:4550 [wandb_init.py:_log_setup():371] Logging user logs to /home/sohui/code/DTC/code/wandb/run-20220218_130458-2d1q5b8s/logs/debug.log
2022-02-18 13:04:58,755 INFO    MainThread:4550 [wandb_init.py:_log_setup():372] Logging internal logs to /home/sohui/code/DTC/code/wandb/run-20220218_130458-2d1q5b8s/logs/debug-internal.log
2022-02-18 13:04:58,756 INFO    MainThread:4550 [wandb_init.py:init():404] calling init triggers
2022-02-18 13:04:58,756 INFO    MainThread:4550 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'mdoel': 'DTC', 'server': 57, 'image size': '112,112,80'}
2022-02-18 13:04:58,757 INFO    MainThread:4550 [wandb_init.py:init():449] starting backend
2022-02-18 13:04:58,757 INFO    MainThread:4550 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-18 13:04:58,773 INFO    MainThread:4550 [backend.py:ensure_launched():199] starting backend process...
2022-02-18 13:04:58,780 INFO    MainThread:4550 [backend.py:ensure_launched():204] started backend process with pid: 4621
2022-02-18 13:04:58,782 INFO    MainThread:4550 [wandb_init.py:init():458] backend started and connected
2022-02-18 13:04:58,785 INFO    MainThread:4550 [wandb_init.py:init():519] updated telemetry
2022-02-18 13:04:58,787 INFO    MainThread:4550 [wandb_init.py:init():549] communicating current version
2022-02-18 13:04:59,628 INFO    MainThread:4550 [wandb_init.py:init():554] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-18 13:04:59,628 INFO    MainThread:4550 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2022-02-18 13:05:00,093 INFO    MainThread:4550 [wandb_init.py:init():592] starting run threads in backend
2022-02-18 13:05:00,338 INFO    MainThread:4550 [wandb_run.py:_console_start():1816] atexit reg
2022-02-18 13:05:00,340 INFO    MainThread:4550 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.REDIRECT
2022-02-18 13:05:00,341 INFO    MainThread:4550 [wandb_run.py:_redirect():1695] Redirecting console.
2022-02-18 13:05:00,345 INFO    MainThread:4550 [wandb_run.py:_redirect():1751] Redirects installed.
2022-02-18 13:05:00,346 INFO    MainThread:4550 [wandb_init.py:init():619] run started, returning control to user process
2022-02-18 13:05:04,070 INFO    MainThread:4550 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2022-02-18 13:05:04,070 INFO    MainThread:4550 [wandb_run.py:_restore():1758] restore
2022-02-18 13:05:06,876 INFO    MainThread:4550 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 598
  total_bytes: 598
}

2022-02-18 13:05:07,051 INFO    MainThread:4550 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 598
  total_bytes: 598
}

2022-02-18 13:05:07,439 INFO    MainThread:4550 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 598
  total_bytes: 598
}

2022-02-18 13:05:08,129 INFO    MainThread:4550 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 598
  total_bytes: 4668
}

2022-02-18 13:05:08,233 INFO    MainThread:4550 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 598
  total_bytes: 4668
}

2022-02-18 13:05:08,336 INFO    MainThread:4550 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 598
  total_bytes: 4668
}

2022-02-18 13:05:08,440 INFO    MainThread:4550 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 598
  total_bytes: 4668
}

2022-02-18 13:05:08,544 INFO    MainThread:4550 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4668
  total_bytes: 4668
}

2022-02-18 13:05:08,647 INFO    MainThread:4550 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4668
  total_bytes: 4668
}

2022-02-18 13:05:08,750 INFO    MainThread:4550 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4668
  total_bytes: 4668
}

2022-02-18 13:05:08,857 INFO    MainThread:4550 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4668
  total_bytes: 4668
}

2022-02-18 13:05:08,960 INFO    MainThread:4550 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4668
  total_bytes: 4668
}

2022-02-18 13:05:09,431 INFO    MainThread:4550 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4668
  total_bytes: 4668
}

2022-02-18 13:05:09,996 INFO    MainThread:4550 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4668
  total_bytes: 4668
}
local_info {
}

2022-02-18 13:05:11,156 INFO    MainThread:4550 [wandb_run.py:_append_files():2184] logging synced files
