2022-02-18 09:35:35,159 INFO    MainThread:1352 [wandb_setup.py:_flush():71] setting env: {}
2022-02-18 09:35:35,159 INFO    MainThread:1352 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-18 09:35:35,159 INFO    MainThread:1352 [wandb_init.py:_log_setup():371] Logging user logs to /home/sohui/code/DTC/code/wandb/run-20220218_093535-2pwumesn/logs/debug.log
2022-02-18 09:35:35,159 INFO    MainThread:1352 [wandb_init.py:_log_setup():372] Logging internal logs to /home/sohui/code/DTC/code/wandb/run-20220218_093535-2pwumesn/logs/debug-internal.log
2022-02-18 09:35:35,160 INFO    MainThread:1352 [wandb_init.py:init():404] calling init triggers
2022-02-18 09:35:35,160 INFO    MainThread:1352 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'mdoel': 'DTC', 'server': 57, 'image size': '112,112,80'}
2022-02-18 09:35:35,161 INFO    MainThread:1352 [wandb_init.py:init():449] starting backend
2022-02-18 09:35:35,161 INFO    MainThread:1352 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-18 09:35:35,176 INFO    MainThread:1352 [backend.py:ensure_launched():199] starting backend process...
2022-02-18 09:35:35,183 INFO    MainThread:1352 [backend.py:ensure_launched():204] started backend process with pid: 1422
2022-02-18 09:35:35,185 INFO    MainThread:1352 [wandb_init.py:init():458] backend started and connected
2022-02-18 09:35:35,187 INFO    MainThread:1352 [wandb_init.py:init():519] updated telemetry
2022-02-18 09:35:35,189 INFO    MainThread:1352 [wandb_init.py:init():549] communicating current version
2022-02-18 09:35:36,073 INFO    MainThread:1352 [wandb_init.py:init():554] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-18 09:35:36,073 INFO    MainThread:1352 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2022-02-18 09:35:36,334 INFO    MainThread:1352 [wandb_init.py:init():592] starting run threads in backend
2022-02-18 09:35:36,561 INFO    MainThread:1352 [wandb_run.py:_console_start():1816] atexit reg
2022-02-18 09:35:36,563 INFO    MainThread:1352 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.REDIRECT
2022-02-18 09:35:36,564 INFO    MainThread:1352 [wandb_run.py:_redirect():1695] Redirecting console.
2022-02-18 09:35:36,569 INFO    MainThread:1352 [wandb_run.py:_redirect():1751] Redirects installed.
2022-02-18 09:35:36,569 INFO    MainThread:1352 [wandb_init.py:init():619] run started, returning control to user process
2022-02-18 09:35:52,429 INFO    MainThread:1352 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 255
2022-02-18 09:35:52,430 INFO    MainThread:1352 [wandb_run.py:_restore():1758] restore
2022-02-18 09:35:54,622 INFO    MainThread:1352 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 604
  total_bytes: 604
}

2022-02-18 09:35:54,802 INFO    MainThread:1352 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 604
  total_bytes: 604
}

2022-02-18 09:35:55,122 INFO    MainThread:1352 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 604
  total_bytes: 604
}

2022-02-18 09:35:55,378 INFO    MainThread:1352 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 604
  total_bytes: 5349
}

2022-02-18 09:35:55,482 INFO    MainThread:1352 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 604
  total_bytes: 5594
}

2022-02-18 09:35:55,585 INFO    MainThread:1352 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 604
  total_bytes: 5594
}

2022-02-18 09:35:55,689 INFO    MainThread:1352 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2095
  total_bytes: 5594
}

2022-02-18 09:35:55,793 INFO    MainThread:1352 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5594
  total_bytes: 5594
}

2022-02-18 09:35:55,896 INFO    MainThread:1352 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5594
  total_bytes: 5594
}

2022-02-18 09:35:55,999 INFO    MainThread:1352 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5594
  total_bytes: 5594
}

2022-02-18 09:35:56,103 INFO    MainThread:1352 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5594
  total_bytes: 5594
}

2022-02-18 09:35:56,207 INFO    MainThread:1352 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5594
  total_bytes: 5594
}

2022-02-18 09:35:56,485 INFO    MainThread:1352 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5594
  total_bytes: 5594
}

2022-02-18 09:35:57,002 INFO    MainThread:1352 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5594
  total_bytes: 5594
}
local_info {
}

