2022-03-02 15:23:22,100 INFO    MainThread:16051 [wandb_setup.py:_flush():71] setting env: {}
2022-03-02 15:23:22,101 INFO    MainThread:16051 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-02 15:23:22,101 INFO    MainThread:16051 [wandb_init.py:_log_setup():371] Logging user logs to /home/sohui/code/DTC/code/wandb/run-20220302_152322-nsqswa9s/logs/debug.log
2022-03-02 15:23:22,101 INFO    MainThread:16051 [wandb_init.py:_log_setup():372] Logging internal logs to /home/sohui/code/DTC/code/wandb/run-20220302_152322-nsqswa9s/logs/debug-internal.log
2022-03-02 15:23:22,101 INFO    MainThread:16051 [wandb_init.py:init():404] calling init triggers
2022-03-02 15:23:22,102 INFO    MainThread:16051 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'mdoel': 'DTC', 'server': 57, 'image size': '112,112,80'}
2022-03-02 15:23:22,102 INFO    MainThread:16051 [wandb_init.py:init():449] starting backend
2022-03-02 15:23:22,102 INFO    MainThread:16051 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-02 15:23:22,135 INFO    MainThread:16051 [backend.py:ensure_launched():199] starting backend process...
2022-03-02 15:23:22,158 INFO    MainThread:16051 [backend.py:ensure_launched():204] started backend process with pid: 16230
2022-03-02 15:23:22,167 INFO    MainThread:16051 [wandb_init.py:init():458] backend started and connected
2022-03-02 15:23:22,171 INFO    MainThread:16051 [wandb_init.py:init():519] updated telemetry
2022-03-02 15:23:22,181 INFO    MainThread:16051 [wandb_init.py:init():549] communicating current version
2022-03-02 15:23:23,348 INFO    MainThread:16051 [wandb_init.py:init():554] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-02 15:23:23,348 INFO    MainThread:16051 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2022-03-02 15:23:23,615 INFO    MainThread:16051 [wandb_init.py:init():592] starting run threads in backend
2022-03-02 15:23:23,909 INFO    MainThread:16051 [wandb_run.py:_console_start():1816] atexit reg
2022-03-02 15:23:23,910 INFO    MainThread:16051 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.REDIRECT
2022-03-02 15:23:23,910 INFO    MainThread:16051 [wandb_run.py:_redirect():1695] Redirecting console.
2022-03-02 15:23:23,916 INFO    MainThread:16051 [wandb_run.py:_redirect():1751] Redirects installed.
2022-03-02 15:23:23,917 INFO    MainThread:16051 [wandb_init.py:init():619] run started, returning control to user process
2022-03-02 15:24:00,861 INFO    MainThread:16051 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2022-03-02 15:24:00,863 INFO    MainThread:16051 [wandb_run.py:_restore():1758] restore
2022-03-02 15:24:03,695 INFO    MainThread:16051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 588
  total_bytes: 588
}

2022-03-02 15:24:03,903 INFO    MainThread:16051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 588
  total_bytes: 588
}

2022-03-02 15:24:04,156 INFO    MainThread:16051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 588
  total_bytes: 588
}

2022-03-02 15:24:04,670 INFO    MainThread:16051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 588
  total_bytes: 5128
}

2022-03-02 15:24:04,774 INFO    MainThread:16051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 588
  total_bytes: 5155
}

2022-03-02 15:24:04,878 INFO    MainThread:16051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 588
  total_bytes: 5155
}

2022-03-02 15:24:04,981 INFO    MainThread:16051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 588
  total_bytes: 5155
}

2022-03-02 15:24:05,084 INFO    MainThread:16051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5155
  total_bytes: 5155
}

2022-03-02 15:24:05,187 INFO    MainThread:16051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5155
  total_bytes: 5155
}

2022-03-02 15:24:05,296 INFO    MainThread:16051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5155
  total_bytes: 5155
}

2022-03-02 15:24:05,400 INFO    MainThread:16051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5155
  total_bytes: 5155
}

2022-03-02 15:24:05,504 INFO    MainThread:16051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5155
  total_bytes: 5155
}

2022-03-02 15:24:05,608 INFO    MainThread:16051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5155
  total_bytes: 5155
}

2022-03-02 15:24:05,859 INFO    MainThread:16051 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5155
  total_bytes: 5155
}

2022-03-02 15:24:06,395 INFO    MainThread:16051 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5155
  total_bytes: 5155
}
local_info {
}

2022-03-02 15:24:07,633 INFO    MainThread:16051 [wandb_run.py:_append_files():2184] logging synced files
