2022-02-06 14:08:22,534 INFO    MainThread:18339 [wandb_setup.py:_flush():71] setting env: {}
2022-02-06 14:08:22,534 INFO    MainThread:18339 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-06 14:08:22,535 INFO    MainThread:18339 [wandb_init.py:_log_setup():371] Logging user logs to /home/sohui/code/DTC/code/wandb/run-20220206_140822-3v4w0939/logs/debug.log
2022-02-06 14:08:22,535 INFO    MainThread:18339 [wandb_init.py:_log_setup():372] Logging internal logs to /home/sohui/code/DTC/code/wandb/run-20220206_140822-3v4w0939/logs/debug-internal.log
2022-02-06 14:08:22,535 INFO    MainThread:18339 [wandb_init.py:init():404] calling init triggers
2022-02-06 14:08:22,536 INFO    MainThread:18339 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'mdoel': 'DTC', 'server': 57, 'image size': '112,112,80'}
2022-02-06 14:08:22,536 INFO    MainThread:18339 [wandb_init.py:init():449] starting backend
2022-02-06 14:08:22,536 INFO    MainThread:18339 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-06 14:08:22,552 INFO    MainThread:18339 [backend.py:ensure_launched():199] starting backend process...
2022-02-06 14:08:22,561 INFO    MainThread:18339 [backend.py:ensure_launched():204] started backend process with pid: 18432
2022-02-06 14:08:22,563 INFO    MainThread:18339 [wandb_init.py:init():458] backend started and connected
2022-02-06 14:08:22,565 INFO    MainThread:18339 [wandb_init.py:init():519] updated telemetry
2022-02-06 14:08:22,567 INFO    MainThread:18339 [wandb_init.py:init():549] communicating current version
2022-02-06 14:08:23,482 INFO    MainThread:18339 [wandb_init.py:init():554] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-06 14:08:23,483 INFO    MainThread:18339 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2022-02-06 14:08:23,748 INFO    MainThread:18339 [wandb_init.py:init():592] starting run threads in backend
2022-02-06 14:08:23,999 INFO    MainThread:18339 [wandb_run.py:_console_start():1816] atexit reg
2022-02-06 14:08:24,000 INFO    MainThread:18339 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.REDIRECT
2022-02-06 14:08:24,000 INFO    MainThread:18339 [wandb_run.py:_redirect():1695] Redirecting console.
2022-02-06 14:08:24,004 INFO    MainThread:18339 [wandb_run.py:_redirect():1751] Redirects installed.
2022-02-06 14:08:24,005 INFO    MainThread:18339 [wandb_init.py:init():619] run started, returning control to user process
2022-02-06 14:08:29,684 INFO    MainThread:18339 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2022-02-06 14:08:29,685 INFO    MainThread:18339 [wandb_run.py:_restore():1758] restore
2022-02-06 14:08:32,060 INFO    MainThread:18339 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 576
  total_bytes: 576
}

2022-02-06 14:08:32,220 INFO    MainThread:18339 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 576
  total_bytes: 576
}

2022-02-06 14:08:32,465 INFO    MainThread:18339 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 576
  total_bytes: 576
}

2022-02-06 14:08:32,785 INFO    MainThread:18339 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 576
  total_bytes: 6110
}

2022-02-06 14:08:32,888 INFO    MainThread:18339 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 576
  total_bytes: 6136
}

2022-02-06 14:08:32,992 INFO    MainThread:18339 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 576
  total_bytes: 6136
}

2022-02-06 14:08:33,095 INFO    MainThread:18339 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 576
  total_bytes: 6136
}

2022-02-06 14:08:33,198 INFO    MainThread:18339 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6136
  total_bytes: 6136
}

2022-02-06 14:08:33,301 INFO    MainThread:18339 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6136
  total_bytes: 6136
}

2022-02-06 14:08:33,405 INFO    MainThread:18339 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6136
  total_bytes: 6136
}

2022-02-06 14:08:33,508 INFO    MainThread:18339 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6136
  total_bytes: 6136
}

2022-02-06 14:08:34,012 INFO    MainThread:18339 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6136
  total_bytes: 6136
}

2022-02-06 14:08:34,532 INFO    MainThread:18339 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6136
  total_bytes: 6136
}
local_info {
}

2022-02-06 14:08:35,693 INFO    MainThread:18339 [wandb_run.py:_append_files():2184] logging synced files
