2022-02-21 03:11:03,178 INFO    MainThread:15097 [internal.py:wandb_internal():87] W&B internal server running at pid: 15097, started at: 2022-02-21 03:11:03.177981
2022-02-21 03:11:03,182 DEBUG   HandlerThread:15097 [handler.py:handle_request():130] handle_request: check_version
2022-02-21 03:11:03,183 INFO    WriterThread:15097 [datastore.py:open_for_write():77] open: /home/sohui/code/DTC/code/wandb/run-20220221_031102-y97j1dhy/run-y97j1dhy.wandb
2022-02-21 03:11:03,187 DEBUG   SenderThread:15097 [sender.py:send():238] send: header
2022-02-21 03:11:03,187 DEBUG   SenderThread:15097 [sender.py:send_request():252] send_request: check_version
2022-02-21 03:11:03,272 DEBUG   SenderThread:15097 [sender.py:send():238] send: run
2022-02-21 03:11:03,550 INFO    SenderThread:15097 [dir_watcher.py:__init__():169] watching files in: /home/sohui/code/DTC/code/wandb/run-20220221_031102-y97j1dhy/files
2022-02-21 03:11:03,551 INFO    SenderThread:15097 [sender.py:_start_run_threads():825] run started: y97j1dhy with start time 1645413062
2022-02-21 03:11:03,551 DEBUG   SenderThread:15097 [sender.py:send():238] send: summary
2022-02-21 03:11:03,552 INFO    SenderThread:15097 [sender.py:_save_file():960] saving file wandb-summary.json with policy end
2022-02-21 03:11:03,555 DEBUG   HandlerThread:15097 [handler.py:handle_request():130] handle_request: run_start
2022-02-21 03:11:03,567 DEBUG   HandlerThread:15097 [meta.py:__init__():40] meta init
2022-02-21 03:11:03,567 DEBUG   HandlerThread:15097 [meta.py:__init__():54] meta init done
2022-02-21 03:11:03,567 DEBUG   HandlerThread:15097 [meta.py:probe():214] probe
2022-02-21 03:11:03,575 DEBUG   HandlerThread:15097 [git.py:repo():33] git repository is invalid
2022-02-21 03:11:03,576 DEBUG   HandlerThread:15097 [meta.py:_save_pip():58] save pip
2022-02-21 03:11:03,576 DEBUG   HandlerThread:15097 [meta.py:_save_pip():72] save pip done
2022-02-21 03:11:03,577 DEBUG   HandlerThread:15097 [meta.py:_save_conda():79] save conda
2022-02-21 03:11:03,585 ERROR   HandlerThread:15097 [meta.py:_save_conda():88] Error saving conda packages
Traceback (most recent call last):
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/site-packages/wandb/sdk/internal/meta.py", line 84, in _save_conda
    subprocess.call(
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
2022-02-21 03:11:03,588 DEBUG   HandlerThread:15097 [meta.py:_save_conda():89] save conda done
2022-02-21 03:11:03,588 DEBUG   HandlerThread:15097 [meta.py:probe():252] probe done
2022-02-21 03:11:03,779 DEBUG   SenderThread:15097 [sender.py:send():238] send: files
2022-02-21 03:11:03,779 INFO    SenderThread:15097 [sender.py:_save_file():960] saving file wandb-metadata.json with policy now
2022-02-21 03:11:03,792 DEBUG   HandlerThread:15097 [handler.py:handle_request():130] handle_request: stop_status
2022-02-21 03:11:03,792 DEBUG   SenderThread:15097 [sender.py:send_request():252] send_request: stop_status
2022-02-21 03:11:04,480 INFO    Thread-11 :15097 [upload_job.py:push():137] Uploaded file /tmp/tmplmccgqicwandb/fxj1t6e2-wandb-metadata.json
2022-02-21 03:11:04,555 INFO    Thread-8  :15097 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220221_031102-y97j1dhy/files/conda-environment.yaml
2022-02-21 03:11:04,555 INFO    Thread-8  :15097 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220221_031102-y97j1dhy/files/wandb-summary.json
2022-02-21 03:11:04,556 INFO    Thread-8  :15097 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220221_031102-y97j1dhy/files/output.log
2022-02-21 03:11:04,556 INFO    Thread-8  :15097 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220221_031102-y97j1dhy/files/wandb-metadata.json
2022-02-21 03:11:04,557 INFO    Thread-8  :15097 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220221_031102-y97j1dhy/files/requirements.txt
2022-02-21 03:11:06,553 INFO    Thread-8  :15097 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sohui/code/DTC/code/wandb/run-20220221_031102-y97j1dhy/files/output.log
2022-02-21 03:11:10,555 INFO    Thread-8  :15097 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sohui/code/DTC/code/wandb/run-20220221_031102-y97j1dhy/files/output.log
2022-02-21 03:11:19,042 DEBUG   HandlerThread:15097 [handler.py:handle_request():130] handle_request: stop_status
2022-02-21 03:11:19,044 DEBUG   SenderThread:15097 [sender.py:send_request():252] send_request: stop_status
2022-02-21 03:11:34,182 DEBUG   SenderThread:15097 [sender.py:send():238] send: stats
2022-02-21 03:11:34,273 DEBUG   HandlerThread:15097 [handler.py:handle_request():130] handle_request: stop_status
2022-02-21 03:11:34,273 DEBUG   SenderThread:15097 [sender.py:send_request():252] send_request: stop_status
2022-02-21 03:11:49,487 DEBUG   HandlerThread:15097 [handler.py:handle_request():130] handle_request: stop_status
2022-02-21 03:11:49,489 DEBUG   SenderThread:15097 [sender.py:send_request():252] send_request: stop_status
2022-02-21 03:12:04,702 DEBUG   HandlerThread:15097 [handler.py:handle_request():130] handle_request: stop_status
2022-02-21 03:12:04,704 DEBUG   SenderThread:15097 [sender.py:send_request():252] send_request: stop_status
2022-02-21 03:12:06,326 DEBUG   SenderThread:15097 [sender.py:send():238] send: stats
2022-02-21 03:12:12,062 WARNING MainThread:15097 [internal.py:wandb_internal():146] Internal process interrupt: 1
